# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
  - oldrel
  - release
  - devel

before_install:
  # Set CXX1X for R-devel, as R-devel does currently not detect CXX1X support for gcc 4.6.3
  # Check if we can remove this at some point in 2017
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi

r_packages:
  - lintr
  - covr
  - drat

after_success:
  - test $TRAVIS_R_VERSION_STRING == "release" &&
    Rscript -e "lintr::lint_package()"
  - test $TRAVIS_R_VERSION_STRING == "release" &&
    Rscript -e "library(covr); coveralls()"
  - test $TRAVIS_PULL_REQUEST == "false" &&
    test $TRAVIS_BRANCH == "master" &&
    test $TRAVIS_R_VERSION_STRING == "release" &&
    bash .travis/deploy_to_drat.sh

